
name: 'kagr_analytics'
version: '1.0.0'
config-version: 2
profile: 'kagr_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"

vars:
  run_date: '2026-10-01'

models:
  kagr_analytics:
    staging:
      +materialized: view
      +tags: ['stg']
      +schema: stg
    intermediate:
      +materialized: view
      +tags: ['int']
      +schema: int
    marts:
      +materialized: table
      +tags: ['marts']
      +schema: marts

