name: 'kagr_analytics'
version: '1.0.0'
config-version: 2
profile: 'kagr_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  archtics_database: 'RAW'
  team_abbr: 'ClientName'
  organization_name: 'River Cats'
  # when seas.organizationid in (1,5) - only ones get the price-code mapping
  stadium_level_org_ids: [1, 5]
  # seat generator
  max_seat_number: 100000

models:
  kagr_analytics:
    staging:
      +materialized: view
      +tags: ['staging', 'archtics']
    intermediate:
      +materialized: view
      +tags: ['intermediate', 'archtics']
    marts:
      +materialized: table
      +tags: ['marts', 'archtics']
      +schema: marts